var punti =
{
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "id": 4, "gid": 31, "definizion": "domus", "descrizion": "Grande domus realizzata nel corso del I secolo d.C., con atrio sul quale si affacciavano vari ambienti, molti dei quali pavimentati a mosaico.", "luogo": "piazza San Giovanni", "dat_in": "I secolo d.C.", "dat_fin": "II secolo d.C.", "id_areasca": 1, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.254700, 43.773174 ] } }
,
{ "type": "Feature", "properties": { "id": 4, "gid": 32, "definizion": "domus", "descrizion": "Grande domus realizzata nel corso del I secolo d.C., con atrio sul quale si affacciavano vari ambienti, molti dei quali pavimentati a mosaico.", "luogo": "piazza San Giovanni", "dat_in": "I secolo d.C.", "dat_fin": "II secolo d.C.", "id_areasca": 1, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.254697, 43.773214 ] } }
,
{ "type": "Feature", "properties": { "id": 4, "gid": 33, "definizion": "domus", "descrizion": "Grande domus realizzata nel corso del I secolo d.C., con atrio sul quale si affacciavano vari ambienti, molti dei quali pavimentati a mosaico.", "luogo": "piazza San Giovanni", "dat_in": "I secolo d.C.", "dat_fin": "II secolo d.C.", "id_areasca": 1, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.254648, 43.773195 ] } }
,
{ "type": "Feature", "properties": { "id": 8, "gid": 120, "definizion": "tempio di Iside", "descrizion": "Recupero di numerosi frammenti marmorei riconducibili a statue e decorazioni architettoniche, alcuni oggetti cultuali e numerose iscrizioni, che hanno permesso di identificare larea con quella del tempio di Iside.", "luogo": "piazza San Firenze", "dat_in": "II secolo d.C.", "dat_fin": "III secolo - IV secolo d.C.?", "id_areasca": 0, "periodo_ve": "Romano", "periodo_co": "r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.257869, 43.769466 ] } }
,
{ "type": "Feature", "properties": { "id": 11, "gid": 39, "definizion": "foro", "descrizion": "Foro della colonia romana, ampliato in et adrianea e caratterizzato da unampia platea circondata  da portici ed edifici monumentali; mantenne le sue prerogative di area pubblica anche in et altomedievale.", "luogo": "piazza della Repubblica\/Mercato Vecchio", "dat_in": "fine I secolo a.C.", "dat_fin": "IV-V secolo (l'area rimase uno spazio commerciale in et medievale)", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.254605, 43.772018 ] } }
,
{ "type": "Feature", "properties": { "id": 14, "gid": 49, "definizion": "necropoli\/sepolture", "descrizion": "Rinvenimento, in varie occasioni, di lucerne fittili, cippi, iscrizioni sepolcrali e di alcune urne funerarie, che fanno supporre la presenza di una necropoli dei primi tempi della colonia.", "luogo": "piazza San Firenze", "dat_in": "fine I secolo a.C.", "dat_fin": "I secolo d.C.", "id_areasca": 0, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.257514, 43.769517 ] } }
,
{ "type": "Feature", "properties": { "id": 14, "gid": 123, "definizion": "necropoli\/sepolture", "descrizion": "Rinvenimento, in varie occasioni, di lucerne fittili, cippi, iscrizioni sepolcrali e di alcune urne funerarie, che fanno supporre la presenza di una necropoli dei primi tempi della colonia.", "luogo": "piazza San Firenze", "dat_in": "fine I secolo a.C.", "dat_fin": "I secolo d.C.", "id_areasca": 0, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.257692, 43.769653 ] } }
,
{ "type": "Feature", "properties": { "id": 17, "gid": 165, "definizion": "necropoli\/sepolture", "descrizion": "Rinvenimento di unurnetta in arenaria e di unolla cineraria; il corredo era costituito da frammenti di vasetti in vetro, una lucerna fittile e due monete bronzee.", "luogo": "via di Valfonda\/piazza Adua", "dat_in": "I secolo d.C.", "dat_fin": "I secolo d.C.", "id_areasca": 123, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.248684, 43.778950 ] } }
,
{ "type": "Feature", "properties": { "id": 18, "gid": 111, "definizion": "necropoli\/sepolture", "descrizion": "Vasta area sepolcrale di epoca imperiale, caratterizzata da tombe a inumazione e a cremazione e da corredi molto poveri.", "luogo": "Fortezza da Basso", "dat_in": "fine I secolo a.C. - inizio I secolo d.C.", "dat_fin": "III secolo d.C.", "id_areasca": 126, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.248970, 43.781488 ] } }
,
{ "type": "Feature", "properties": { "id": 18, "gid": 112, "definizion": "necropoli\/sepolture", "descrizion": "Vasta area sepolcrale di epoca imperiale, caratterizzata da tombe a inumazione e a cremazione e da corredi molto poveri.", "luogo": "Fortezza da Basso", "dat_in": "fine I secolo a.C. - inizio I secolo d.C.", "dat_fin": "III secolo d.C.", "id_areasca": 125, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.249407, 43.780623 ] } }
,
{ "type": "Feature", "properties": { "id": 18, "gid": 164, "definizion": "necropoli\/sepolture", "descrizion": "Vasta area sepolcrale di epoca imperiale, caratterizzata da tombe a inumazione e a cremazione e da corredi molto poveri.", "luogo": "Fortezza da Basso", "dat_in": "fine I secolo a.C. - inizio I secolo d.C.", "dat_fin": "III secolo d.C.", "id_areasca": 59, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.246929, 43.780860 ] } }
,
{ "type": "Feature", "properties": { "id": 19, "gid": 129, "definizion": "necropoli\/sepolture", "descrizion": "Recupero di tre stele di arenaria, una grande lapide marmorea, ed un fondo di anfora con bollo, che fanno supporre la presenza di una necropoli  nellarea .", "luogo": "via di San Gallo", "dat_in": "fine I secolo a.C.-inizio I secolo d.C.", "dat_fin": "III secolo d.C. ?", "id_areasca": 128, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.262223, 43.784341 ] } }
,
{ "type": "Feature", "properties": { "id": 19, "gid": 166, "definizion": "necropoli\/sepolture", "descrizion": "Recupero di tre stele di arenaria, una grande lapide marmorea, ed un fondo di anfora con bollo, che fanno supporre la presenza di una necropoli  nellarea .", "luogo": "via di San Gallo", "dat_in": "fine I secolo a.C.-inizio I secolo d.C.", "dat_fin": "III secolo d.C. ?", "id_areasca": 127, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.257291, 43.778491 ] } }
,
{ "type": "Feature", "properties": { "id": 21, "gid": 163, "definizion": "domus", "descrizion": "Scoperta di un pavimento in cocciopesto sotto la chiesa di San Benedetto. Datazione incerta.", "luogo": "chiesa di San Benedetto", "dat_in": "datazione incerta", "dat_fin": "datazione incerta", "id_areasca": 109, "periodo_ve": "Dubbio", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.257047, 43.772303 ] } }
,
{ "type": "Feature", "properties": { "id": 23, "gid": 146, "definizion": "domus", "descrizion": "Pavimento a mosaico, posato su uno strato di smalto di cocciopesto a sua volta steso su uno strato di smalto bianco e renone.", "luogo": "vicolo dell'Onest", "dat_in": "II secolo d.C.", "dat_fin": "?", "id_areasca": 111, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.255059, 43.771184 ] } }
,
{ "type": "Feature", "properties": { "id": 24, "gid": 52, "definizion": "edificio non determinabile", "descrizion": "Resti di un edificio con muri rivestiti di bozze di pietra disposte a filaretto.", "luogo": "via del Corso\/chiesa di S.Margherita", "dat_in": "Datazione incerta (epoca imperiale?)", "dat_fin": "Datazione incerta (epoca imperiale?)", "id_areasca": 10, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.256334, 43.771512 ] } }
,
{ "type": "Feature", "properties": { "id": 25, "gid": 128, "definizion": "domus", "descrizion": "Pavimento in cocciopesto mescolato con pezzetti di marmo, di 13,50 per 7,50 metri, pertinente ad un edificio che si affacciava sulla via decumana.", "luogo": "via del Corso\/via del Presto", "dat_in": "fine I secolo a.C.", "dat_fin": "?", "id_areasca": 112, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.257583, 43.771453 ] } }
,
{ "type": "Feature", "properties": { "id": 26, "gid": 143, "definizion": "domus", "descrizion": "Resti di edifici romani, costituiti da varie fondazioni di muri e un pavimento in opus spicatum, sul quale giaceva il fusto di una colonna.", "luogo": "vicolo d'Orsanmichele \/ via Calimala", "dat_in": "I secolo d.C.", "dat_fin": "?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.254787, 43.770583 ] } }
,
{ "type": "Feature", "properties": { "id": 30, "gid": 142, "definizion": "domus", "descrizion": "Resti di due pavimenti in cocciopesto a quote simili e a breve distanza tra loro.", "luogo": "*via del Fuoco*\/ via Calimala", "dat_in": "I secolo d.C.", "dat_fin": "?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.254345, 43.770756 ] } }
,
{ "type": "Feature", "properties": { "id": 32, "gid": 138, "definizion": "domus", "descrizion": "Strutture murarie romane e raccolta di numerosi pezzi di cornici e decorazioni marmoree, pertinenti ad una ricca abitazione.", "luogo": "Logge del Mercato Nuovo", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r1" }, "geometry": { "type": "Point", "coordinates": [ 11.254223, 43.770258 ] } }
,
{ "type": "Feature", "properties": { "id": 33, "gid": 156, "definizion": "domus\/edificio produttivo", "descrizion": "Tre vasche intercomunicanti e rivestite dintonaco impermeabile.", "luogo": "chiesa di S. Gaetano", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 118, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.252063, 43.772362 ] } }
,
{ "type": "Feature", "properties": { "id": 34, "gid": 160, "definizion": "domus", "descrizion": "Pavimento a mosaico con decorazione geometrica, messo in relazione ad una casa edificata lungo la strada consolare.", "luogo": "borgo S.Lorenzo", "dat_in": "fine I secolo a.C.-I secolo d.C.", "dat_fin": "?", "id_areasca": 97, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.255207, 43.774431 ] } }
,
{ "type": "Feature", "properties": { "id": 35, "gid": 161, "definizion": "domus", "descrizion": "Ambiente pavimentato a cocciopesto; in un angolo della stanza furono trovate due anfore.", "luogo": "via Martelli presso l'entrata del Liceo Galilei", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 62, "periodo_ve": "Romano", "periodo_co": "r1" }, "geometry": { "type": "Point", "coordinates": [ 11.255595, 43.774370 ] } }
,
{ "type": "Feature", "properties": { "id": 36, "gid": 169, "definizion": "edificio non determinabile", "descrizion": "Notizia del ritrovamento di resti di edifici romani e di frammenti statuari.", "luogo": "Croce al Trebbio", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 96, "periodo_ve": "Romano", "periodo_co": "rd" }, "geometry": { "type": "Point", "coordinates": [ 11.250312, 43.773076 ] } }
,
{ "type": "Feature", "properties": { "id": 37, "gid": 157, "definizion": "edificio produttivo", "descrizion": "Resti di alcuni muri perfettamente orientati col reticolo stradale romano e a poca distanza da essi presenza di un bacino e due vasche (una rettangolare e una semicircolare) comunicanti e dotate di unintonacatura impermeabile.", "luogo": "via dei Boni", "dat_in": "I-II secolo d.C.", "dat_fin": "?", "id_areasca": 116, "periodo_ve": "Romano", "periodo_co": "r1\/r2" }, "geometry": { "type": "Point", "coordinates": [ 11.252621, 43.773166 ] } }
,
{ "type": "Feature", "properties": { "id": 39, "gid": 168, "definizion": "domus", "descrizion": "Pavimenti lastricati in marmo di et adrianea soprastanti impiantiti in opus tessellatum di et giulio-claudia e pi antichi pavimenti in cocciopesto. A poca distanza sono venuti alla luce i resti di una grande vasca.", "luogo": "via dei Pescioni", "dat_in": "fine I secolo a.C.- I secolo d.C.", "dat_fin": "III-IV secolo d.C.?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.252343, 43.772354 ] } }
,
{ "type": "Feature", "properties": { "id": 42, "gid": 152, "definizion": "domus", "descrizion": "Pavimenti sovrapposti ad un probabile impianto artigianale (tre vasche). Poco pi e sud altri muri attribuiti alla prima fase della colonia.", "luogo": "via Tosinghi", "dat_in": "fine I secolo a.C.-I secolo d.C.", "dat_fin": "?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r4" }, "geometry": { "type": "Point", "coordinates": [ 11.253942, 43.772492 ] } }
,
{ "type": "Feature", "properties": { "id": 42, "gid": 153, "definizion": "domus", "descrizion": "Pavimenti sovrapposti ad un probabile impianto artigianale (tre vasche). Poco pi e sud altri muri attribuiti alla prima fase della colonia.", "luogo": "via Tosinghi", "dat_in": "fine I secolo a.C.-I secolo d.C.", "dat_fin": "?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r3" }, "geometry": { "type": "Point", "coordinates": [ 11.253942, 43.772477 ] } }
,
{ "type": "Feature", "properties": { "id": 43, "gid": 47, "definizion": "edificio abitativo\/buche di palo", "descrizion": "Individuazione di un muro divisorio e di buche di palo che vanno ad interessare alcuni ambienti a mosaico delle terme e della domus.", "luogo": "piazza S.Giovani", "dat_in": "IV secolo d.C.?", "dat_fin": "V-VI secolo d.C.?", "id_areasca": 1, "periodo_ve": "Romano", "periodo_co": "r4\/m2" }, "geometry": { "type": "Point", "coordinates": [ 11.254704, 43.773266 ] } }
,
{ "type": "Feature", "properties": { "id": 47, "gid": 137, "definizion": "domus", "descrizion": "Pavimento in cocciopesto.", "luogo": "via Porta Rossa", "dat_in": "datazione incerta (epoca imperiale?)", "dat_fin": "datazione incerta", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r1" }, "geometry": { "type": "Point", "coordinates": [ 11.251487, 43.770255 ] } }
,
{ "type": "Feature", "properties": { "id": 48, "gid": 136, "definizion": "domus", "descrizion": "Resti di alcuni impiantiti in cocciopesto.", "luogo": "via delle Terme", "dat_in": "fine I secolo a.C..-I secolo d.C.", "dat_fin": "?", "id_areasca": 115, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.252351, 43.770091 ] } }
,
{ "type": "Feature", "properties": { "id": 49, "gid": 131, "definizion": "domus", "descrizion": "Scoperta di tracce di alcuni pavimenti in cocciopesto.", "luogo": "piazza Davanzati", "dat_in": "datazione incerta (epoca imperiale?)", "dat_fin": "?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.252653, 43.770132 ] } }
,
{ "type": "Feature", "properties": { "id": 50, "gid": 130, "definizion": "domus", "descrizion": "Pavimento composto da detriti di mattore e marmo, spesso 20 cm circa. 1,5 metri sotto questo  pavimento furono inoltre raccolti frammenti di tre piccole coppe dargento.", "luogo": "piazza Davanzati", "dat_in": "fine I secolo a.C--I secolo d.C.", "dat_fin": "?", "id_areasca": 114, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.252898, 43.770191 ] } }
,
{ "type": "Feature", "properties": { "id": 51, "gid": 148, "definizion": "edificio non determinabile", "descrizion": "Resti di costruzioni romane caratterizzate da bozze a filaretto.", "luogo": "piazza S.Biagio", "dat_in": "datazione incerta", "dat_fin": "datazione incerta", "id_areasca": 104, "periodo_ve": "Romano", "periodo_co": "rd\/md" }, "geometry": { "type": "Point", "coordinates": [ 11.253641, 43.769797 ] } }
,
{ "type": "Feature", "properties": { "id": 52, "gid": 170, "definizion": "domus", "descrizion": "Pavimento in cocciopesto, sopra il quale furono raccolti vari oggetti di et romana.", "luogo": "via Brunelleschi \/ via del Campidoglio", "dat_in": "fine I secolo a.C. - inizio I secolo d.C.", "dat_fin": "?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.253458, 43.772302 ] } }
,
{ "type": "Feature", "properties": { "id": 53, "gid": 149, "definizion": "terme", "descrizion": "Resti di costruzioni romane, costituiti da colonnette, riferibili forse allimpianto di riscaldamento termale di una ricca abitazione, o pi probabilmente delle vicine terme del Capaccio.", "luogo": "Mercato Nuovo", "dat_in": "fine I secolo d.C-II secolo d.C.", "dat_fin": "IV secolo d.C. - inizi V secolo d.C. ?", "id_areasca": 0, "periodo_ve": "Romano", "periodo_co": "r1" }, "geometry": { "type": "Point", "coordinates": [ 11.254243, 43.770030 ] } }
,
{ "type": "Feature", "properties": { "id": 54, "gid": 122, "definizion": "edificio non determinabile", "descrizion": "Resti di costruzioni e frammenti ceramici.", "luogo": "via Ghibellina", "dat_in": "datazione incerta (epoca imperiale?)", "dat_fin": "datazione incerta", "id_areasca": 91, "periodo_ve": "Romano", "periodo_co": "r1" }, "geometry": { "type": "Point", "coordinates": [ 11.260941, 43.770977 ] } }
,
{ "type": "Feature", "properties": { "id": 55, "gid": 30, "definizion": "edificio non determinabile", "descrizion": "Resti di strutture murarie.", "luogo": "piazza S.Trinita", "dat_in": "datazione incerta", "dat_fin": "datazione incerta", "id_areasca": 72, "periodo_ve": "Romano", "periodo_co": "r1" }, "geometry": { "type": "Point", "coordinates": [ 11.251148, 43.770099 ] } }
,
{ "type": "Feature", "properties": { "id": 61, "gid": 144, "definizion": "domus", "descrizion": "Pavimento romano attribuito alla prima fase della colonia romana, in cocciopesto con intarsi di piccole lastre di marmo irregolarmente disposte di vari colori e forme.", "luogo": "via de'Magazzini", "dat_in": "fine I secolo a.C.- inizi I secolo d.C.", "dat_fin": "?", "id_areasca": 0, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.256846, 43.770665 ] } }
,
{ "type": "Feature", "properties": { "id": 62, "gid": 151, "definizion": "edificio non determinabile", "descrizion": "Notizia del rinvenimento di resti non meglio identificati di edifici romani.", "luogo": "via de'Cerretani", "dat_in": "datazione incerta", "dat_fin": "datazione incerta", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "rd\/md" }, "geometry": { "type": "Point", "coordinates": [ 11.253587, 43.773275 ] } }
,
{ "type": "Feature", "properties": { "id": 63, "gid": 135, "definizion": "edificio non determinabile", "descrizion": "\"Muraglione\" ascrivibile allepoca romana. Dentro una pietra quadra forata furono rinvenute tre monete di et imperiale.", "luogo": "piazza del Carmine", "dat_in": "?", "dat_fin": "III secolo d.C.- IV secolo d.C?", "id_areasca": 0, "periodo_ve": "Romano", "periodo_co": "r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.243875, 43.768242 ] } }
,
{ "type": "Feature", "properties": { "id": 64, "gid": 127, "definizion": "porta\/cinta muraria", "descrizion": "Notizia del rinvenimento dei resti della porta urbica orientale pertinenti alla cinta muraria romana, nel Medioevo detta porta San Piero.", "luogo": "via del Corso\/via del Presto", "dat_in": "fine I secolo a.C.- inizi I secolo d.C.", "dat_fin": "?", "id_areasca": 88, "periodo_ve": "Romano", "periodo_co": "r2\/r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.257812, 43.771475 ] } }
,
{ "type": "Feature", "properties": { "id": 65, "gid": 145, "definizion": "edificio abitativo\/buche di palo", "descrizion": "Resti di abitazioni precarie erette tra le murature di un complesso termale abbandonato, costituiti da pozzi scavati nel pavimento e numerose buche di palo impostate su un sottile strato di riporto.", "luogo": "piazza Signoria", "dat_in": "fine IV secolo d.C.-V secolo d.C.", "dat_fin": "?", "id_areasca": 78, "periodo_ve": "Romano", "periodo_co": "r4" }, "geometry": { "type": "Point", "coordinates": [ 11.255783, 43.769904 ] } }
,
{ "type": "Feature", "properties": { "id": 66, "gid": 139, "definizion": "discarica", "descrizion": "Ampio strato di scarico, al cui interno sono stati raccolti vari materiali archeologici che indicano un uso dellarea come discarica dal tardo I secolo a.C. fino agli inizi del II secolo d.C., quando fu costruita una strada.", "luogo": "borgo SS.Apostoli\/piazza S.Trinita", "dat_in": "fine I secolo a.C.", "dat_fin": "fine I secolo d.C.", "id_areasca": 72, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.252635, 43.769284 ] } }
,
{ "type": "Feature", "properties": { "id": 71, "gid": 155, "definizion": "strada e fognatura", "descrizion": "Rinvenimento di una strada e di una fogna di epoca romana.", "luogo": "via Brunelleschi", "dat_in": "I secolo a.C. - I secolo d.C.", "dat_fin": "IV-V secolo d.C. ?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2\/r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.253596, 43.772054 ] } }
,
{ "type": "Feature", "properties": { "id": 72, "gid": 121, "definizion": "domus", "descrizion": "Notizia dello scavo parziale nel XVI secolo di un ricco edificio romano, di cui furono osservati i resti di un pavimento e di rivestimenti parietali in opus sectile.", "luogo": "borgo de'Greci", "dat_in": "II-III secolo d.C.?", "dat_fin": "?", "id_areasca": 0, "periodo_ve": "Romano", "periodo_co": "r2\/r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.258501, 43.769294 ] } }
,
{ "type": "Feature", "properties": { "id": 73, "gid": 150, "definizion": "domus", "descrizion": "Pavimento costruito da detriti di mattone e marmo, alcuni frammenti di decorazioni marmoree e un capitello.", "luogo": "chiesa di San Gaetano", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 118, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.252055, 43.772382 ] } }
,
{ "type": "Feature", "properties": { "id": 74, "gid": 134, "definizion": "domus", "descrizion": "Resti di pavimento a mosaico a tessere bianche e nere vicino ad un impluvium contornato con lastre di pietra serena.", "luogo": "via Pellicceria", "dat_in": "fine I secolo a.C.-I secolo d.C.", "dat_fin": "?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.253346, 43.770798 ] } }
,
{ "type": "Feature", "properties": { "id": 75, "gid": 133, "definizion": "edificio produttivo", "descrizion": "Due vasche abbinate di forma quadrilatera.", "luogo": "piazza Davanzati \/ via porta Rossa", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.252837, 43.770299 ] } }
,
{ "type": "Feature", "properties": { "id": 76, "gid": 132, "definizion": "domus\/edificio produttivo", "descrizion": "Abbondanti resti di pavimenti in cocciopesto e un frammento di pavimento a mosaico, a cui si associano tre vasche rettangolari prive di unapparente comunicazione e con pareti interne ben intonacate.", "luogo": "via Pellicceria \/ palazzo delle Poste", "dat_in": "fine I secolo a.C-I secolo d.C.", "dat_fin": "?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.253122, 43.770527 ] } }
,
{ "type": "Feature", "properties": { "id": 88, "gid": 48, "definizion": "area cimiteriale\/sepolture", "descrizion": "Rinvenimento di sepolture tipologicamente non omogenee sorte sui resti di edifici di et imperiale e tardo antichi.", "luogo": "piazza S.Giovanni\/episcopio", "dat_in": "IV-V secolo d.C.", "dat_fin": "XIII secolo", "id_areasca": 0, "periodo_ve": "Romano", "periodo_co": "r4\/m2" }, "geometry": { "type": "Point", "coordinates": [ 11.254898, 43.772961 ] } }
,
{ "type": "Feature", "properties": { "id": 89, "gid": 140, "definizion": "struttura in muratura", "descrizion": "Resti sulle due sponde dellArno di due lunghe e larghe fondazioni in calcestruzzo.", "luogo": "piazza del Pesce", "dat_in": "datazione incerta", "dat_fin": "datazione incerta", "id_areasca": 0, "periodo_ve": "Romano", "periodo_co": "rd\/md" }, "geometry": { "type": "Point", "coordinates": [ 11.253716, 43.768378 ] } }
,
{ "type": "Feature", "properties": { "id": 90, "gid": 147, "definizion": "domus", "descrizion": "Pavimento in cocciopesto.", "luogo": "via dei Bardi", "dat_in": "datazione incerta (epoca imperiale?)", "dat_fin": "datazione incerta (epoca imperiale?)", "id_areasca": 0, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.253342, 43.767146 ] } }
,
{ "type": "Feature", "properties": { "id": 91, "gid": 154, "definizion": "fognatura", "descrizion": "Tratto di fognatura costruito con materiale di recupero, tra cui figurano tre frammenti di statue, di vari pavimenti e rivestimenti marmorei e un capitello tuscanico usato come copertuta.", "luogo": "via Tosinghi\/*via della Nave*", "dat_in": "fine I secolo a.C.-I secolo d.C.", "dat_fin": "IV-V secolo d.C. ?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r4" }, "geometry": { "type": "Point", "coordinates": [ 11.254489, 43.772201 ] } }
,
{ "type": "Feature", "properties": { "id": 95, "gid": 21, "definizion": "fortificazione\/torre\/Gardingo", "descrizion": "Lemiciclo del teatro fu riutilizzato come caposaldo militare e forse sul lato sud del teatro venne costruita  una torre di guardia in epoca Longobarda, da cui  il nome di Guardingo che rimase come toponimo alla zona sino al bassomedioevo.", "luogo": "palazzo Vecchio", "dat_in": "VI-VII secolo d.C.", "dat_fin": "?", "id_areasca": 70, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3" }, "geometry": { "type": "Point", "coordinates": [ 11.257028, 43.768976 ] } }
,
{ "type": "Feature", "properties": { "id": 117, "gid": 20, "definizion": "ponte\/piloni di ponte", "descrizion": "resti di strutture, probabilmente ponte o ponti sul Mugnone", "luogo": "piazza S.Marco\/via Cavour", "dat_in": "medievale?", "dat_fin": "medievale?", "id_areasca": 0, "periodo_ve": "Medioevo", "periodo_co": "md" }, "geometry": { "type": "Point", "coordinates": [ 11.256167, 43.777108 ] } }
,
{ "type": "Feature", "properties": { "id": 117, "gid": 118, "definizion": "ponte\/piloni di ponte", "descrizion": "resti di strutture, probabilmente ponte o ponti sul Mugnone", "luogo": "piazza S.Marco\/via Cavour", "dat_in": "medievale?", "dat_fin": "medievale?", "id_areasca": 0, "periodo_ve": "Medioevo", "periodo_co": "md" }, "geometry": { "type": "Point", "coordinates": [ 11.258401, 43.777917 ] } }
,
{ "type": "Feature", "properties": { "id": 118, "gid": 117, "definizion": "area cimiteriale\/sepolture", "descrizion": "Gruppo di sepolture con copertura a lastre e muretti divisori. Reimpiego di materiali romani.", "luogo": "*vie del Refe Nero*\/*via degli Agli*, attuale via del Campidoglio", "dat_in": "IV-VII secolo?", "dat_fin": "?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r4\/m2" }, "geometry": { "type": "Point", "coordinates": [ 11.252882, 43.772236 ] } }
,
{ "type": "Feature", "properties": { "id": 120, "gid": 167, "definizion": "edificio non determinabile\/terme?", "descrizion": "Struttura in muratura, forse attribuibile ad epoca romana.", "luogo": "piazza Madonna \/ San Lorenzo", "dat_in": "epoca imperiale?", "dat_fin": "epoca imperiale?", "id_areasca": 61, "periodo_ve": "Romano", "periodo_co": "r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.253371, 43.774782 ] } }
,
{ "type": "Feature", "properties": { "id": 121, "gid": 119, "definizion": "cinta muraria", "descrizion": "Tratto della cinta del 1172-1175", "luogo": "via Martelli\/via dei Ginori", "dat_in": "fine XII secolo", "dat_fin": "XIVsecolo", "id_areasca": 154, "periodo_ve": "Medioevo", "periodo_co": "m3" }, "geometry": { "type": "Point", "coordinates": [ 11.255475, 43.774922 ] } }
,
{ "type": "Feature", "properties": { "id": 122, "gid": 110, "definizion": "necropoli\/sepolture", "descrizion": "Sepolture presso una strada romana", "luogo": "viale Belfiore", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 60, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.243399, 43.782368 ] } }
,
{ "type": "Feature", "properties": { "id": 123, "gid": 109, "definizion": "strada", "descrizion": "Resti di strada romana", "luogo": "viale Belfiore", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 60, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.243419, 43.782349 ] } }
,
{ "type": "Feature", "properties": { "id": 124, "gid": 108, "definizion": "strada", "descrizion": "Strada posta ad un metro sopra la strada romana (probabilmente medievale)", "luogo": "viale Belfiore", "dat_in": "epoca medievale ?", "dat_fin": "epoca medievale ?", "id_areasca": 60, "periodo_ve": "Medioevo", "periodo_co": "md" }, "geometry": { "type": "Point", "coordinates": [ 11.243378, 43.782338 ] } }
,
{ "type": "Feature", "properties": { "id": 125, "gid": 107, "definizion": "fossato\/fosso", "descrizion": "Fossato che circondava a Nord la Fortezza da Basso", "luogo": "via Caduti dei Lager", "dat_in": "XVI secolo", "dat_fin": "?", "id_areasca": 124, "periodo_ve": "Età moderna", "periodo_co": "d2\/d3\/d4" }, "geometry": { "type": "Point", "coordinates": [ 11.247280, 43.782769 ] } }
,
{ "type": "Feature", "properties": { "id": 126, "gid": 106, "definizion": "domus", "descrizion": "Pavimentazione in cocciopesto e anfore intere databili al II secolo d.C. relative ad un edificio.", "luogo": "viale Strozzi", "dat_in": "II secolo d.C.", "dat_fin": "?", "id_areasca": 58, "periodo_ve": "Romano", "periodo_co": "r3" }, "geometry": { "type": "Point", "coordinates": [ 11.248575, 43.780073 ] } }
,
{ "type": "Feature", "properties": { "id": 137, "gid": 105, "definizion": "edificio non determinabile", "descrizion": "Muretto divisorio che frazione l'ambiente del tepidarium nelle terme di piazza Signoria.", "luogo": "piazza Signoria", "dat_in": "fine IV secolo d.C.- prima met V secolo d.C.", "dat_fin": "?", "id_areasca": 78, "periodo_ve": "Romano", "periodo_co": "r4" }, "geometry": { "type": "Point", "coordinates": [ 11.255803, 43.769673 ] } }
,
{ "type": "Feature", "properties": { "id": 139, "gid": 104, "definizion": "edificio non determinabile", "descrizion": "Riutilizzo della latrina del complesso adrianeo.", "luogo": "piazza Signoria", "dat_in": "fine IV secolo- V secolo d.C.", "dat_fin": "?", "id_areasca": 78, "periodo_ve": "Romano", "periodo_co": "r4" }, "geometry": { "type": "Point", "coordinates": [ 11.255441, 43.769826 ] } }
,
{ "type": "Feature", "properties": { "id": 140, "gid": 103, "definizion": "edificio abitativo", "descrizion": "Edificio abitativo realizzato presso i resti del portico delle terme.", "luogo": "piazza Signoria", "dat_in": "fine IV - V secolo d.C.", "dat_fin": "?", "id_areasca": 78, "periodo_ve": "Romano", "periodo_co": "r4" }, "geometry": { "type": "Point", "coordinates": [ 11.255576, 43.769721 ] } }
,
{ "type": "Feature", "properties": { "id": 143, "gid": 102, "definizion": "fognatura", "descrizion": "Alcuni grandi fosse per la manutenzione dei condotti fognari.", "luogo": "piazza Signoria", "dat_in": "fine IV - V secolo d.C.", "dat_fin": "VI secolo d.C. ?", "id_areasca": 78, "periodo_ve": "Romano", "periodo_co": "r4\/m2" }, "geometry": { "type": "Point", "coordinates": [ 11.255936, 43.769732 ] } }
,
{ "type": "Feature", "properties": { "id": 146, "gid": 10, "definizion": "edificio non determinabile", "descrizion": "Murature a secco, piani di calpestio, riempimenti, focolari", "luogo": "piazza Signoria", "dat_in": "VI-VII secolo d.C.?", "dat_fin": "VIII-IX secolo ?", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2" }, "geometry": { "type": "Point", "coordinates": [ 11.255880, 43.769731 ] } }
,
{ "type": "Feature", "properties": { "id": 146, "gid": 11, "definizion": "edificio non determinabile", "descrizion": "Murature a secco, piani di calpestio, riempimenti, focolari", "luogo": "piazza Signoria", "dat_in": "VI-VII secolo d.C.?", "dat_fin": "VIII-IX secolo ?", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2" }, "geometry": { "type": "Point", "coordinates": [ 11.255915, 43.769862 ] } }
,
{ "type": "Feature", "properties": { "id": 147, "gid": 97, "definizion": "area cimiteriale\/sepolture", "descrizion": "Area cimiteriale in relazione alla basilica paleocristiana e poi alla basilica medievale di S.Cecilia", "luogo": "piazza Signoria", "dat_in": "VI secolo d.C.", "dat_fin": "XIV secolo", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3\/m4" }, "geometry": { "type": "Point", "coordinates": [ 11.255440, 43.769661 ] } }
,
{ "type": "Feature", "properties": { "id": 147, "gid": 98, "definizion": "area cimiteriale\/sepolture", "descrizion": "Area cimiteriale in relazione alla basilica paleocristiana e poi alla basilica medievale di S.Cecilia", "luogo": "piazza Signoria", "dat_in": "VI secolo d.C.", "dat_fin": "XIV secolo", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3\/m4" }, "geometry": { "type": "Point", "coordinates": [ 11.255377, 43.769808 ] } }
,
{ "type": "Feature", "properties": { "id": 147, "gid": 99, "definizion": "area cimiteriale\/sepolture", "descrizion": "Area cimiteriale in relazione alla basilica paleocristiana e poi alla basilica medievale di S.Cecilia", "luogo": "piazza Signoria", "dat_in": "VI secolo d.C.", "dat_fin": "XIV secolo", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3\/m4" }, "geometry": { "type": "Point", "coordinates": [ 11.255285, 43.769577 ] } }
,
{ "type": "Feature", "properties": { "id": 147, "gid": 100, "definizion": "area cimiteriale\/sepolture", "descrizion": "Area cimiteriale in relazione alla basilica paleocristiana e poi alla basilica medievale di S.Cecilia", "luogo": "piazza Signoria", "dat_in": "VI secolo d.C.", "dat_fin": "XIV secolo", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3\/m4" }, "geometry": { "type": "Point", "coordinates": [ 11.255268, 43.769651 ] } }
,
{ "type": "Feature", "properties": { "id": 147, "gid": 101, "definizion": "area cimiteriale\/sepolture", "descrizion": "Area cimiteriale in relazione alla basilica paleocristiana e poi alla basilica medievale di S.Cecilia", "luogo": "piazza Signoria", "dat_in": "VI secolo d.C.", "dat_fin": "XIV secolo", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3\/m4" }, "geometry": { "type": "Point", "coordinates": [ 11.255299, 43.769723 ] } }
,
{ "type": "Feature", "properties": { "id": 148, "gid": 95, "definizion": "sepolture", "descrizion": "Sepolture isolate forse in associazione ad abitazioni.", "luogo": "piazza Signoria", "dat_in": "VI secolo d.C. ?", "dat_fin": "VII-VIII secolo d.C. ?", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2" }, "geometry": { "type": "Point", "coordinates": [ 11.255886, 43.769703 ] } }
,
{ "type": "Feature", "properties": { "id": 148, "gid": 96, "definizion": "sepolture", "descrizion": "Sepolture isolate forse in associazione ad abitazioni.", "luogo": "piazza Signoria", "dat_in": "VI secolo d.C. ?", "dat_fin": "VII-VIII secolo d.C. ?", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2" }, "geometry": { "type": "Point", "coordinates": [ 11.255588, 43.769727 ] } }
,
{ "type": "Feature", "properties": { "id": 149, "gid": 94, "definizion": "area cimiteriale\/sepolture", "descrizion": "Serie di sepolture allienate lungo una direttrice viaria.", "luogo": "piazza Signoria", "dat_in": "IX-X secolo ?", "dat_fin": "XI secolo ?", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2" }, "geometry": { "type": "Point", "coordinates": [ 11.255602, 43.769514 ] } }
,
{ "type": "Feature", "properties": { "id": 150, "gid": 93, "definizion": "area cimiteriale\/sepolture", "descrizion": "Serie di sepolture allienate lungo una probabile direttrice viaria est-ovest.", "luogo": "piazza Signoria", "dat_in": "IX-X secolo ?", "dat_fin": "XI secolo ?", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2" }, "geometry": { "type": "Point", "coordinates": [ 11.255710, 43.769821 ] } }
,
{ "type": "Feature", "properties": { "id": 151, "gid": 91, "definizion": "edificio non determinabile", "descrizion": "Strutture in muratura e in legno riferibili al XI-inizi XII secolo.", "luogo": "piazza Signoria", "dat_in": "fine X secolo-primi XI secolo ?", "dat_fin": "XII secolo", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3" }, "geometry": { "type": "Point", "coordinates": [ 11.255754, 43.769693 ] } }
,
{ "type": "Feature", "properties": { "id": 151, "gid": 92, "definizion": "edificio non determinabile", "descrizion": "Strutture in muratura e in legno riferibili al XI-inizi XII secolo.", "luogo": "piazza Signoria", "dat_in": "fine X secolo-primi XI secolo ?", "dat_fin": "XII secolo", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3" }, "geometry": { "type": "Point", "coordinates": [ 11.255379, 43.769840 ] } }
,
{ "type": "Feature", "properties": { "id": 157, "gid": 90, "definizion": "strada\/piazza", "descrizion": "Pavimentazione relativa probabilmente ad una piccola piazza.", "luogo": "piazza Signoria", "dat_in": "XIII secolo", "dat_fin": "inizi XIV secolo", "id_areasca": 78, "periodo_ve": "Medioevo", "periodo_co": "m4" }, "geometry": { "type": "Point", "coordinates": [ 11.256203, 43.769727 ] } }
,
{ "type": "Feature", "properties": { "id": 165, "gid": 89, "definizion": "strada", "descrizion": "Strada romana", "luogo": "via del Proconsolo", "dat_in": "fine I secolo a.C.- I secolo d.C.", "dat_fin": "IV secolo d.C.?", "id_areasca": 54, "periodo_ve": "Romano", "periodo_co": "r2\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.257685, 43.770845 ] } }
,
{ "type": "Feature", "properties": { "id": 167, "gid": 88, "definizion": "area cimiteriale\/sepolture", "descrizion": "Sepolture", "luogo": "via del Proconsolo", "dat_in": "IV-V secolo d.C.", "dat_fin": "epoca medievale (sepolture della Badia) ?", "id_areasca": 79, "periodo_ve": "Romano", "periodo_co": "r4\/md" }, "geometry": { "type": "Point", "coordinates": [ 11.257791, 43.770796 ] } }
,
{ "type": "Feature", "properties": { "id": 168, "gid": 86, "definizion": "strada", "descrizion": "Strada medievale", "luogo": "via del Proconsolo", "dat_in": "met XIII secolo", "dat_fin": "?", "id_areasca": 135, "periodo_ve": "Medioevo", "periodo_co": "m4" }, "geometry": { "type": "Point", "coordinates": [ 11.257846, 43.770503 ] } }
,
{ "type": "Feature", "properties": { "id": 168, "gid": 87, "definizion": "strada", "descrizion": "Strada medievale", "luogo": "via del Proconsolo", "dat_in": "met XIII secolo", "dat_fin": "?", "id_areasca": 52, "periodo_ve": "Medioevo", "periodo_co": "m4" }, "geometry": { "type": "Point", "coordinates": [ 11.257851, 43.770734 ] } }
,
{ "type": "Feature", "properties": { "id": 178, "gid": 84, "definizion": "area cimiteriale\/sepolture", "descrizion": "Sepolcri e sepolture", "luogo": "Ospedale di Santa Maria Nuova", "dat_in": "XV secolo", "dat_fin": "XVII secolo", "id_areasca": 51, "periodo_ve": "Medioevo", "periodo_co": "m5\/d2\/d3" }, "geometry": { "type": "Point", "coordinates": [ 11.259715, 43.773702 ] } }
,
{ "type": "Feature", "properties": { "id": 182, "gid": 83, "definizion": "area cimiteriale\/sepolture", "descrizion": "Due sepolture senza corredo tagliate su un piano di calpestio (strada?)", "luogo": "chiesa di San Lorenzo", "dat_in": "(VI secolo ?)  XI secolo ?", "dat_fin": "XII secolo ?", "id_areasca": 131, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3" }, "geometry": { "type": "Point", "coordinates": [ 11.254095, 43.775021 ] } }
,
{ "type": "Feature", "properties": { "id": 183, "gid": 81, "definizion": "strada", "descrizion": "Piano di calpestio probabilmente riferibile ad una strada", "luogo": "chiesa di San Lorenzo", "dat_in": "XI-XII secolo ?", "dat_fin": "?", "id_areasca": 131, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3" }, "geometry": { "type": "Point", "coordinates": [ 11.254090, 43.775023 ] } }
,
{ "type": "Feature", "properties": { "id": 184, "gid": 82, "definizion": "chiesa di San Lorenzo", "descrizion": "Chiesa di San Lorenzo", "luogo": "San Lorenzo", "dat_in": "fine IV secolo d.C.", "dat_fin": "esistente", "id_areasca": 131, "periodo_ve": "Romano", "periodo_co": "m3" }, "geometry": { "type": "Point", "coordinates": [ 11.254119, 43.775011 ] } }
,
{ "type": "Feature", "properties": { "id": 186, "gid": 77, "definizion": "area cimiteriale\/sepolture", "descrizion": "Tombe e sepolcri al di sotto della chiesa e piazza attuale di Santa Felicita", "luogo": "chiesa e piazza di Santa Felicita", "dat_in": "XI secolo ? (in fase con la basilica romanica?)", "dat_fin": "XVI - XVIII secolo", "id_areasca": 168, "periodo_ve": "Medioevo", "periodo_co": "m3\/m4\/" }, "geometry": { "type": "Point", "coordinates": [ 11.252411, 43.767006 ] } }
,
{ "type": "Feature", "properties": { "id": 186, "gid": 79, "definizion": "area cimiteriale\/sepolture", "descrizion": "Tombe e sepolcri al di sotto della chiesa e piazza attuale di Santa Felicita", "luogo": "chiesa e piazza di Santa Felicita", "dat_in": "XI secolo ? (in fase con la basilica romanica?)", "dat_fin": "XVI - XVIII secolo", "id_areasca": 169, "periodo_ve": "Medioevo", "periodo_co": "d2\/d3\/d4\/" }, "geometry": { "type": "Point", "coordinates": [ 11.252665, 43.766714 ] } }
,
{ "type": "Feature", "properties": { "id": 186, "gid": 80, "definizion": "area cimiteriale\/sepolture", "descrizion": "Tombe e sepolcri al di sotto della chiesa e piazza attuale di Santa Felicita", "luogo": "chiesa e piazza di Santa Felicita", "dat_in": "XI secolo ? (in fase con la basilica romanica?)", "dat_fin": "XVI - XVIII secolo", "id_areasca": 169, "periodo_ve": "Medioevo", "periodo_co": "d1" }, "geometry": { "type": "Point", "coordinates": [ 11.252678, 43.766720 ] } }
,
{ "type": "Feature", "properties": { "id": 188, "gid": 78, "definizion": "strada\/piazza", "descrizion": "Lastricato a basoli", "luogo": "piazza di Santa Felicita", "dat_in": "XIII-XIV secolo ?", "dat_fin": "XVIII secolo ?", "id_areasca": 168, "periodo_ve": "Medioevo", "periodo_co": "m4?\/m5\/d2\/d3\/d4?" }, "geometry": { "type": "Point", "coordinates": [ 11.252419, 43.767013 ] } }
,
{ "type": "Feature", "properties": { "id": 189, "gid": 76, "definizion": "dark layers", "descrizion": "Strato di 'terreno vegetale', forse 'dark layer'", "luogo": "Piazza di Santa Felicita", "dat_in": "VII-VIII secolo ?", "dat_fin": "X-XI secolo ?", "id_areasca": 168, "periodo_ve": "Medioevo", "periodo_co": "m2" }, "geometry": { "type": "Point", "coordinates": [ 11.252428, 43.767017 ] } }
,
{ "type": "Feature", "properties": { "id": 192, "gid": 75, "definizion": "edificio non determinabile", "descrizion": "Tratto di pavimento in calcestruzzo", "luogo": "piazza dei Rossi \/ piazza S. Felicita", "dat_in": "epoca imperiale ?", "dat_fin": "epoca imperiale ?", "id_areasca": 166, "periodo_ve": "Romano", "periodo_co": "rd" }, "geometry": { "type": "Point", "coordinates": [ 11.252660, 43.767008 ] } }
,
{ "type": "Feature", "properties": { "id": 204, "gid": 74, "definizion": "strato alluvionale\/alluvione", "descrizion": "Strato alluvionale spesso 35-40 cm", "luogo": "via Por Santa Maria", "dat_in": "alluvione del 589?", "dat_fin": "alluvione del 589?", "id_areasca": 85, "periodo_ve": "Romano", "periodo_co": "r4\/m2" }, "geometry": { "type": "Point", "coordinates": [ 11.253766, 43.769091 ] } }
,
{ "type": "Feature", "properties": { "id": 205, "gid": 115, "definizion": "strada", "descrizion": "Lastrico formato da grandi basoli di pietraforte sul quale si appoggiava uno strato con ceramica medievale", "luogo": "via Por Santa Maria - via Lambertesca", "dat_in": "XIII-XIV secolo ?", "dat_fin": "?", "id_areasca": 155, "periodo_ve": "Medioevo", "periodo_co": "m3\/m4" }, "geometry": { "type": "Point", "coordinates": [ 11.253918, 43.768971 ] } }
,
{ "type": "Feature", "properties": { "id": 206, "gid": 114, "definizion": "edificio non determinabile", "descrizion": "Fondazione romana in opera a sacco riutilizzata dagli edifici medievali", "luogo": "via por Santa Maria - via Lambertesca", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 155, "periodo_ve": "Romano", "periodo_co": "r1" }, "geometry": { "type": "Point", "coordinates": [ 11.253912, 43.768983 ] } }
,
{ "type": "Feature", "properties": { "id": 211, "gid": 73, "definizion": "strada", "descrizion": "Strada romana presso la postierla sud-occidentale delle mura", "luogo": "via Porta Rossa", "dat_in": "fine I secolo a.C. - inizio I secolo d.C.", "dat_fin": "IV-V secolo ?", "id_areasca": 72, "periodo_ve": "Romano", "periodo_co": "r2\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.251007, 43.770323 ] } }
,
{ "type": "Feature", "properties": { "id": 212, "gid": 71, "definizion": "strato alluvionale\/alluvione", "descrizion": "Strato alluvionale, forse relativo al corso del Mugnone", "luogo": "via delle Belle Donne - Croce al Trebbio", "dat_in": "XI-XII secolo ?", "dat_fin": "XI-XII secolo ?", "id_areasca": 24, "periodo_ve": "Medioevo", "periodo_co": "m2" }, "geometry": { "type": "Point", "coordinates": [ 11.250401, 43.773348 ] } }
,
{ "type": "Feature", "properties": { "id": 213, "gid": 69, "definizion": "area cimiteriale\/sepolture", "descrizion": "Resti di almeno 5 sepolture senza corredo", "luogo": "via delle Belle Donne - Croce al Trebbio", "dat_in": "X secolo ?", "dat_fin": "X secolo ?", "id_areasca": 24, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3" }, "geometry": { "type": "Point", "coordinates": [ 11.250396, 43.773338 ] } }
,
{ "type": "Feature", "properties": { "id": 214, "gid": 68, "definizion": "area produttiva?", "descrizion": "Resti di produzione di oggetti in osso", "luogo": "via delle Belle Donne - Croce al Trebbio", "dat_in": "X secolo ?", "dat_fin": "XI-XII secolo ?", "id_areasca": 24, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3" }, "geometry": { "type": "Point", "coordinates": [ 11.250400, 43.773335 ] } }
,
{ "type": "Feature", "properties": { "id": 215, "gid": 67, "definizion": "area produttiva?", "descrizion": "Scarichi di lavorazione provenienti da attivit metallurgiche", "luogo": "via delle Belle Donne - Croce al Trebbio", "dat_in": "IV-V secolo d.C. ?", "dat_fin": "?", "id_areasca": 24, "periodo_ve": "Romano", "periodo_co": "r4" }, "geometry": { "type": "Point", "coordinates": [ 11.250403, 43.773332 ] } }
,
{ "type": "Feature", "properties": { "id": 216, "gid": 66, "definizion": "area produttiva\/scarti di fornace", "descrizion": "Scarico di fornace per la produzione di vetro", "luogo": "via delle Belle Donne - Croce al Trebbio", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 24, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.250406, 43.773329 ] } }
,
{ "type": "Feature", "properties": { "id": 226, "gid": 63, "definizion": "edificio non determinabile\/produttivo?", "descrizion": "Edificio produttivo lungo il fosso scheraggio.", "luogo": "via Del Proconsolo \/ via di San Procolo", "dat_in": "XI-XII secolo ?", "dat_fin": "XII-XIII secolo", "id_areasca": 17, "periodo_ve": "Medioevo", "periodo_co": "m3" }, "geometry": { "type": "Point", "coordinates": [ 11.258093, 43.770959 ] } }
,
{ "type": "Feature", "properties": { "id": 226, "gid": 64, "definizion": "edificio non determinabile\/produttivo?", "descrizion": "Edificio produttivo lungo il fosso scheraggio.", "luogo": "via Del Proconsolo \/ via di San Procolo", "dat_in": "XI-XII secolo ?", "dat_fin": "XII-XIII secolo", "id_areasca": 17, "periodo_ve": "Medioevo", "periodo_co": "m3" }, "geometry": { "type": "Point", "coordinates": [ 11.258044, 43.770960 ] } }
,
{ "type": "Feature", "properties": { "id": 227, "gid": 65, "definizion": "struttura in muratura", "descrizion": "Lacerto di struttura muraria", "luogo": "via Del Proconsolo \/ via di San Procolo", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 17, "periodo_ve": "Romano", "periodo_co": "r1" }, "geometry": { "type": "Point", "coordinates": [ 11.258056, 43.770982 ] } }
,
{ "type": "Feature", "properties": { "id": 230, "gid": 62, "definizion": "paleoalveo\/fosso\/torrente", "descrizion": "Alveo di un corso d'acqua orientato est-ovest con due fasi successive di interramento", "luogo": "via dei Cerretani \/ piazza S. Giovanni \/ ex Canonica", "dat_in": "?", "dat_fin": "fine I secolo  - inizi II secolo d.C.", "id_areasca": 16, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.255114, 43.773752 ] } }
,
{ "type": "Feature", "properties": { "id": 231, "gid": 61, "definizion": "area cimiteriale\/sepolture", "descrizion": "Area di sepoltura al di sotto del pavimento della chiesa di Sant'Apollonia", "luogo": "via San Gallo - chiesa di Sant'Apollonia", "dat_in": "met XV secolo", "dat_fin": "1866", "id_areasca": 15, "periodo_ve": "Medioevo", "periodo_co": "m5\/dt\/c2" }, "geometry": { "type": "Point", "coordinates": [ 11.256551, 43.777956 ] } }
,
{ "type": "Feature", "properties": { "id": 233, "gid": 60, "definizion": "edificio non determinabile", "descrizion": "Fase di occupazione antecedente al monastero benedettino di Sant'Apollonia", "luogo": "via San Gallo - chiesa di Sant'Apollonia", "dat_in": "XII secolo ?", "dat_fin": "XIV secolo", "id_areasca": 15, "periodo_ve": "Medioevo", "periodo_co": "M3\/M4" }, "geometry": { "type": "Point", "coordinates": [ 11.256547, 43.778001 ] } }
,
{ "type": "Feature", "properties": { "id": 234, "gid": 59, "definizion": "strato alluvionale\/alluvione", "descrizion": "Strato alluvionale", "luogo": "via San Gallo - chiesa di Sant'Apollonia", "dat_in": "V-VI secolo ?", "dat_fin": "?", "id_areasca": 15, "periodo_ve": "Romano", "periodo_co": "r4\/m2\/m3" }, "geometry": { "type": "Point", "coordinates": [ 11.256482, 43.777978 ] } }
,
{ "type": "Feature", "properties": { "id": 235, "gid": 57, "definizion": "necropoli\/sepolture", "descrizion": "Necropoli tardo antica", "luogo": "via San Gallo - chiesa di Sant'Apollonia", "dat_in": "II secolo d.C.", "dat_fin": "IV-V secolo ?", "id_areasca": 15, "periodo_ve": "Romano", "periodo_co": "r4" }, "geometry": { "type": "Point", "coordinates": [ 11.256539, 43.777913 ] } }
,
{ "type": "Feature", "properties": { "id": 235, "gid": 58, "definizion": "necropoli\/sepolture", "descrizion": "Necropoli tardo antica", "luogo": "via San Gallo - chiesa di Sant'Apollonia", "dat_in": "II secolo d.C.", "dat_fin": "IV-V secolo ?", "id_areasca": 14, "periodo_ve": "Romano", "periodo_co": "r4" }, "geometry": { "type": "Point", "coordinates": [ 11.256516, 43.777836 ] } }
,
{ "type": "Feature", "properties": { "id": 236, "gid": 56, "definizion": "strato alluvionale\/alluvione", "descrizion": "Due livelli sabbiosi dello spessore di circa 40 cm di origine alluvionale", "luogo": "via dei Benci \/ Palazzo Busini Bardi", "dat_in": "XIII-XIV secolo", "dat_fin": "XIII-XIV secolo", "id_areasca": 13, "periodo_ve": "Medioevo", "periodo_co": "m4" }, "geometry": { "type": "Point", "coordinates": [ 11.258624, 43.767457 ] } }
,
{ "type": "Feature", "properties": { "id": 237, "gid": 55, "definizion": "strada", "descrizion": "Serie di tre livelli di calpestio in terra battuta", "luogo": "via dei Benci \/ Palazzo Busini Bardi", "dat_in": "XIII secolo", "dat_fin": "XIII secolo", "id_areasca": 13, "periodo_ve": "Medioevo", "periodo_co": "m4" }, "geometry": { "type": "Point", "coordinates": [ 11.258646, 43.767462 ] } }
,
{ "type": "Feature", "properties": { "id": 238, "gid": 54, "definizion": "edificio abitativo", "descrizion": "Edificio con arco di fondazione", "luogo": "via dei Benci \/ Palazzo Busini Bardi", "dat_in": "fine XIII", "dat_fin": "XIV secolo", "id_areasca": 12, "periodo_ve": "Medioevo", "periodo_co": "m4" }, "geometry": { "type": "Point", "coordinates": [ 11.258692, 43.767497 ] } }
,
{ "type": "Feature", "properties": { "id": 240, "gid": 53, "definizion": "domus", "descrizion": "Pavimento in cocciopesto", "luogo": "via dei Vecchietti", "dat_in": "fine I secolo a.C. - I secolo d.C.", "dat_fin": "?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2" }, "geometry": { "type": "Point", "coordinates": [ 11.252882, 43.772010 ] } }
,
{ "type": "Feature", "properties": { "id": 241, "gid": 44, "definizion": "strada e fognatura", "descrizion": "Strada romana con relativa fognatura", "luogo": "via del Corso \/ chiesa di S. Margherita", "dat_in": "fine I secolo a.C. -  I secolo d.C.", "dat_fin": "IV-V secolo d.C. ?", "id_areasca": 10, "periodo_ve": "Romano", "periodo_co": "r2\/r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.256382, 43.771487 ] } }
,
{ "type": "Feature", "properties": { "id": 261, "gid": 51, "definizion": "area cimiteriale\/sepolture", "descrizion": "Sepolcri formati da muri a secco, e coperti di lastre in pietra", "luogo": "*piazza S. Andrea* \/ piazza della Repubblica", "dat_in": "IX-X secolo ?", "dat_fin": "?", "id_areasca": 77, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3\/m4" }, "geometry": { "type": "Point", "coordinates": [ 11.254090, 43.771198 ] } }
,
{ "type": "Feature", "properties": { "id": 269, "gid": 50, "definizion": "strato alluvionale\/alluvione", "descrizion": "Strati alluvionali rinvenuti presso il foro", "luogo": "via della nave", "dat_in": "V-VI secolo ?", "dat_fin": "V-VI secolo ?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r4\/m2" }, "geometry": { "type": "Point", "coordinates": [ 11.254702, 43.772131 ] } }
,
{ "type": "Feature", "properties": { "id": 284, "gid": 40, "definizion": "strada e fognatura", "descrizion": "Strada romana con fognatura. Sopra la strada romana una complessa stratigrafia relativa alla strada medievale.", "luogo": "via Pellicceria", "dat_in": "fine I secolo a.C. - I secolo d.C.", "dat_fin": "lastricato medievale (XIII secolo ?)", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "m2\/m3\/m4" }, "geometry": { "type": "Point", "coordinates": [ 11.253594, 43.771177 ] } }
,
{ "type": "Feature", "properties": { "id": 287, "gid": 116, "definizion": "cinta muraria", "descrizion": "Tratto di fondazione delle mura romane", "luogo": "via dell'Oriuolo \/ piazza del Duomo", "dat_in": "fine I secolo a.C. - inizi I secolo d.C.", "dat_fin": "?", "id_areasca": 65, "periodo_ve": "Romano", "periodo_co": "r2\/r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.257819, 43.772605 ] } }
,
{ "type": "Feature", "properties": { "id": 293, "gid": 43, "definizion": "strada", "descrizion": "Strada romana", "luogo": "borgo SS. Apostoli", "dat_in": "fine I secolo d.C.", "dat_fin": "IV-V secolo d.C.", "id_areasca": 72, "periodo_ve": "Romano", "periodo_co": "r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.252805, 43.769245 ] } }
,
{ "type": "Feature", "properties": { "id": 294, "gid": 42, "definizion": "strada", "descrizion": "Strada, probabilmente di epoca medievale", "luogo": "borgo SS. Apostoli", "dat_in": "XIII-XIV secolo", "dat_fin": "?", "id_areasca": 72, "periodo_ve": "Medioevo", "periodo_co": "m1" }, "geometry": { "type": "Point", "coordinates": [ 11.252930, 43.769207 ] } }
,
{ "type": "Feature", "properties": { "id": 295, "gid": 41, "definizion": "strada", "descrizion": "Strada romana", "luogo": "via Calzaioli \/ vicolo del Porco", "dat_in": "fine I secolo a.C.-inizi I secolo d.C.", "dat_fin": "IV-V secolo d.C.", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2\/r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.255313, 43.772314 ] } }
,
{ "type": "Feature", "properties": { "id": 298, "gid": 38, "definizion": "strada e fognatura", "descrizion": "Strada romana, decumano minore", "luogo": "*via degli Zuffanelli* \/ via del Campidoglio", "dat_in": "fine I secolo a.C.-inizi I secolo d.C.", "dat_fin": "IV-V secolo d.C. ?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2\/r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.252608, 43.772183 ] } }
,
{ "type": "Feature", "properties": { "id": 299, "gid": 37, "definizion": "strada", "descrizion": "Strada Romana", "luogo": "piazza S. Giovanni", "dat_in": "fine I secolo a.C.-inizi I secolo d.C.", "dat_fin": "IV-V secolo d.C. ?", "id_areasca": 77, "periodo_ve": "Romano", "periodo_co": "r2\/r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.254713, 43.772796 ] } }
,
{ "type": "Feature", "properties": { "id": 300, "gid": 36, "definizion": "cinta muraria", "descrizion": "Mura in pillore di fiume impostate sulle fondazioni delle mura romane.", "luogo": "piazza S. Giovanni \/ via de' Cerretani", "dat_in": "epoca medievale", "dat_fin": "epoca medievale", "id_areasca": 1, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3" }, "geometry": { "type": "Point", "coordinates": [ 11.254723, 43.773332 ] } }
,
{ "type": "Feature", "properties": { "id": 301, "gid": 35, "definizion": "cinta muraria", "descrizion": "Fondazione delle mura romane", "luogo": "piazza S. Giovanni \/ via de' Cerretani", "dat_in": "fine I secolo a.C.-inizi I secolo d.C.", "dat_fin": "?", "id_areasca": 1, "periodo_ve": "Romano", "periodo_co": "r2\/r3" }, "geometry": { "type": "Point", "coordinates": [ 11.254727, 43.773333 ] } }
,
{ "type": "Feature", "properties": { "id": 302, "gid": 34, "definizion": "strada e fognatura", "descrizion": "Strada pomerale romana con fognatura", "luogo": "piazza S. Giovanni \/ via dei Cerretani", "dat_in": "fine I secolo a.C. - inizi I secolo d.C.", "dat_fin": "IV-V secolo d.C. ?", "id_areasca": 1, "periodo_ve": "Romano", "periodo_co": "r2\/r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.254741, 43.773297 ] } }
,
{ "type": "Feature", "properties": { "id": 304, "gid": 29, "definizion": "necropoli\/sepolture", "descrizion": "Necropoli romana con tombe monumentali", "luogo": "piazza e chiesa di Santa Felicita", "dat_in": "epoca imperiale", "dat_fin": "epoca imperiale", "id_areasca": 168, "periodo_ve": "Romano", "periodo_co": "r3\/r4" }, "geometry": { "type": "Point", "coordinates": [ 11.252373, 43.767084 ] } }
,
{ "type": "Feature", "properties": { "id": 305, "gid": 28, "definizion": "arco monumentale\/cinta muraria", "descrizion": "Arco monumentale, porta della citt?", "luogo": "piazza San Firenze", "dat_in": "epoca imperiale", "dat_fin": "riutilizzato dalla cinta altomedievale ?", "id_areasca": 153, "periodo_ve": "Romano", "periodo_co": "r1\/m2\/m3" }, "geometry": { "type": "Point", "coordinates": [ 11.257588, 43.770019 ] } }
,
{ "type": "Feature", "properties": { "id": 308, "gid": 27, "definizion": "fognatura", "descrizion": "Resti di una fogna in cui si erano riadoperati come materiale da costruzione frammenti di decorazione marmorea di edifici precedenti.", "luogo": "piazza San Giovanni", "dat_in": "IV-V secolo ?", "dat_fin": "IV-V secolo ?", "id_areasca": 0, "periodo_ve": "Romano", "periodo_co": "r4\/m2" }, "geometry": { "type": "Point", "coordinates": [ 11.254930, 43.772970 ] } }
,
{ "type": "Feature", "properties": { "id": 309, "gid": 25, "definizion": "area cimiteriale\/sepolture", "descrizion": "Sepolture tardoantiche, altomedievali, impostate esternamente lungo il lato meridionale delle mura", "luogo": "via Vacchereccia \/ piazza Signoria", "dat_in": "IV-V secolo ?", "dat_fin": "VI-VII secolo", "id_areasca": 56, "periodo_ve": "Romano", "periodo_co": "r4\/m2" }, "geometry": { "type": "Point", "coordinates": [ 11.255739, 43.769283 ] } }
,
{ "type": "Feature", "properties": { "id": 309, "gid": 26, "definizion": "area cimiteriale\/sepolture", "descrizion": "Sepolture tardoantiche, altomedievali, impostate esternamente lungo il lato meridionale delle mura", "luogo": "via Vacchereccia \/ piazza Signoria", "dat_in": "IV-V secolo ?", "dat_fin": "VI-VII secolo", "id_areasca": 56, "periodo_ve": "Romano", "periodo_co": "r4\/m2" }, "geometry": { "type": "Point", "coordinates": [ 11.255426, 43.769372 ] } }
,
{ "type": "Feature", "properties": { "id": 310, "gid": 24, "definizion": "strada", "descrizion": "Strada, serie di piani di calpestio", "luogo": "piazza Signoria \/ Loggia dei Lanzi", "dat_in": "XI-XII secolo ?", "dat_fin": "esistente", "id_areasca": 56, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3\/m4\/m5" }, "geometry": { "type": "Point", "coordinates": [ 11.255440, 43.769351 ] } }
,
{ "type": "Feature", "properties": { "id": 311, "gid": 23, "definizion": "area cimiteriale\/sepolture", "descrizion": "Sepolture all'interno di Palazzo Vecchio poste in uno spazio presso il teatro romano", "luogo": "palazzo Vecchio", "dat_in": "V secolo ?", "dat_fin": "VII secolo ?", "id_areasca": 70, "periodo_ve": "Romano", "periodo_co": "r4\/m2" }, "geometry": { "type": "Point", "coordinates": [ 11.257072, 43.768982 ] } }
,
{ "type": "Feature", "properties": { "id": 312, "gid": 22, "definizion": "edificio produttivo?", "descrizion": "Tre vasche con scarichi d'acqua", "luogo": "Duomo \/Santa Reparata", "dat_in": "I-II secolo d.C. ?", "dat_fin": "IV-V secolo d.C. ?", "id_areasca": 2, "periodo_ve": "Romano", "periodo_co": "r2\/r3\/" }, "geometry": { "type": "Point", "coordinates": [ 11.255980, 43.773306 ] } }
,
{ "type": "Feature", "properties": { "id": 313, "gid": 12, "definizion": "area produttiva?", "descrizion": "Strati di scorie ferrose", "luogo": "via Por Santa Maria", "dat_in": "epoca medievale", "dat_fin": "epoca medievale", "id_areasca": 85, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3\/" }, "geometry": { "type": "Point", "coordinates": [ 11.253743, 43.769027 ] } }
,
{ "type": "Feature", "properties": { "id": 315, "gid": 16, "definizion": "area cimiteriale\/sepolture", "descrizion": "Resti di tre fosse (una in terra, le altre in costruzione) scavate in strati con materiali di IV-V secolo", "luogo": "Uffizi \/ San Pier Scheraggio", "dat_in": "post IV-V secolo? Datazione incerta", "dat_fin": "post IV-V secolo", "id_areasca": 66, "periodo_ve": "Romano", "periodo_co": "r4\/m2" }, "geometry": { "type": "Point", "coordinates": [ 11.256010, 43.768816 ] } }
,
{ "type": "Feature", "properties": { "id": 318, "gid": 17, "definizion": "area cimiteriale\/sepolture", "descrizion": "Area cimiteriale relativa alla chiesa di San Pier Scheraggio", "luogo": "San Pier Scheraggio", "dat_in": "X secolo ?", "dat_fin": "XV secolo", "id_areasca": 66, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3\/m4\/m5\/" }, "geometry": { "type": "Point", "coordinates": [ 11.256039, 43.768823 ] } }
,
{ "type": "Feature", "properties": { "id": 319, "gid": 15, "definizion": "strada", "descrizion": "Pavimentazione in mattoni", "luogo": "piazza San Giovanni", "dat_in": "XII-XIII secolo ?", "dat_fin": "?", "id_areasca": 1, "periodo_ve": "Medioevo", "periodo_co": "m2\/m3\/m4" }, "geometry": { "type": "Point", "coordinates": [ 11.254818, 43.773230 ] } }
,
{ "type": "Feature", "properties": { "id": 320, "gid": 14, "definizion": "strada", "descrizion": "Lastrico stradale, probabilmente bassomedievale", "luogo": "piazza San Giovanni - *via dell'Arcivescovado*", "dat_in": "XIII secolo ?", "dat_fin": "?", "id_areasca": 1, "periodo_ve": "Medioevo", "periodo_co": "r4?\/m4\/m5" }, "geometry": { "type": "Point", "coordinates": [ 11.254477, 43.773166 ] } }
,
{ "type": "Feature", "properties": { "id": 321, "gid": 13, "definizion": "strada", "descrizion": "Latricati stradali medievali", "luogo": "via Por Santa Maria", "dat_in": "XIII secolo ?", "dat_fin": "?", "id_areasca": 84, "periodo_ve": "Medioevo", "periodo_co": "m4\/m5\/dt" }, "geometry": { "type": "Point", "coordinates": [ 11.254451, 43.769814 ] } }
,
{ "type": "Feature", "properties": { "id": 324, "gid": 19, "definizion": "torre", "descrizion": "Torre", "luogo": "via Roma \/ *via dell'Arcivescovado*", "dat_in": "XII-XIII secolo ?", "dat_fin": "Trasformata in casa poi demolita nel 1894", "id_areasca": 77, "periodo_ve": "Medioevo", "periodo_co": "33\/m4" }, "geometry": { "type": "Point", "coordinates": [ 11.254500, 43.772682 ] } }
,
{ "type": "Feature", "properties": { "id": 325, "gid": 18, "definizion": "torre", "descrizion": "Torre", "luogo": "piazza S. Giovanni \/ *Volta dei Pecori*", "dat_in": "XII-XIII secolo", "dat_fin": "Trasformata in casa poi demolita nel 1894", "id_areasca": 77, "periodo_ve": "Medioevo", "periodo_co": "m3\/m4" }, "geometry": { "type": "Point", "coordinates": [ 11.254493, 43.772800 ] } }

]
};
